config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations'}, sign_up: 'signup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  resources :categories
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :searches
  resources :networks do
    resources :whitepapers, :links, :coins
  end
  resources :links do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  match 'networks/:network_id/coins/:id/logs', to:'coins#logs', via: 'get'
  match 'networks/:id/logs', to:'networks#logs', via: 'get'

  match '/search', to:"searches#results", via: "get"

  match '/account/', to:"users#edit", via: "get"
  match '/account/:id', to:"users#edit", via: "get"

  match '/about', to:'application#about', via: 'get'

  match 'finish/:id/', to: 'users#finish', :as => :finish, via: "get"

  match ':id/', to: 'users#show', via: "get"

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'signin', to: 'devise/sessions#new'
  end



end

app/models/network.rb
class Network < ApplicationRecord

	has_many :coins
	has_and_belongs_to_many :links
	has_many :comments, through: :links
	has_many :whitepapers
	accepts_nested_attributes_for :whitepapers
	belongs_to :category, optional: true
	belongs_to :user, optional: true
	mount_uploader :logo, NetworkLogoUploader
	extend FriendlyId
	include PgSearch
	multisearchable :against => [:name, :description]
	pg_search_scope :search, :against => :name, :using => { :tsearch => { :prefix => true }, :trigram => { :threshold => 0.1 } }

	validates_uniqueness_of :name

	friendly_id :name, use: [:slugged, :history]

	has_paper_trail :class_name => 'Version', :ignore => [:slug, :updated_at, :category_id]

	enum network_status_options: [:concept, :preproduction, :live, :dead]
=begin
	def whitepapers
	    read_attribute(:whitepapers).map {|w| Whitepaper.new(w) }
	end

	class Whitepaper
		attr_accessor :title, :url, :pdf

		def initialize(hash)
		  @title = hash['title']
		  @url = hash['url']
		  @pdf = hash['pdf'].force_encoding("UTF-8")
		end

		def persisted?() false; end
		def new_record?() false; end
		def marked_for_destruction?() false; end
		def _destroy() false; end

	end

	def whitepapers_attributes=(attributes)
		whitepapers = []
		attributes.each do |index, attrs|
		  next if '1' == attrs.delete("_destroy")
		  whitepapers << attrs
		end
		whitepaper_changed(whitepapers)
	end

	def build_whitepaper
		w = self.whitepapers.dup
		w << Whitepaper.new({title: '', url: '', pdf: ''})
		self.whitepapers = w
	end

	def whitepaper_changed(whitepapers)
	    any_changes = false
	    if self.whitepapers.length != whitepapers.length
	      any_changes = true
	    else
	      self.whitepapers.each_with_index do |whitepaper, i|
	        if whitepaper.title != whitepapers[i]["title"] || whitepaper.url != whitepapers[i]["url"] || whitepaper.pdf != whitepapers[i]["pdf"]
	          any_changes = true
	        end
	      end
	    end
	    if any_changes
	      write_attribute(:whitepapers, whitepapers)
	    end
  	end
=end

end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController

	before_action :authenticate_user!, only: [:edit,:new,:create,:update]

	def index
		@networks = Network.all
		@categories = Category.all.order("name ASC")
		page_title = "networks"
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def links
		@links = Network.friendly.find(params[:id]).links
		@network = Network.friendly.find(params[:id])
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def trollbox

	end

	def logs
        network_logs = NetworkService.new
        @network = Network.friendly.find(params[:id]) 
        logs = network_logs.get_logs(@network, "network_log").reverse
        @logs = logs.paginate(:page => params[:page], :per_page => 10)
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end	

	def whitepapers
        @whitepapers = Network.friendly.find(params[:id]).whitepapers
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end		

	def show
		@network = Network.friendly.find(params[:id])
		@whitepapers = @network.whitepapers.all
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def new
		@use_ajax = false
		@network = Network.new
		@network.whitepapers.build
	end

	def edit
		@use_ajax = true
		@network = Network.friendly.find(params[:id])
		@network.whitepapers.build
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def create
		@network = Network.new(network_params)
		@network.user = current_user
	    if @network.save
			redirect_to @network
		else
	        render 'new'
	    end
	end

	def update
		@network = Network.friendly.find(params[:id])
		@network.founders = params[:founders] 
	  	if @network.update_attributes(network_params)
	    	redirect_to @network
		else
	    	render 'edit'
	  	end
	end

	def destroy
		@network.destroy
	end

	private

	    def network_params
	    	params.require(:network).permit(:name, :description, :category_id, :link, :slack, :team, :status, :forum, :coin_id, :logo, :founders, :coin, whitepapers_attributes: [:id, :network_id, :whitepaper_title, :whitepaper, :slug], link_ids: [], founders: [], category_ids: [], coin_ids: [], coins: [])
	    end

end

app/helpers/networks_helper.rb
module NetworksHelper


end

app/views/networks/_category_menu.html.erb
<div class="col-md-2 col-md-offset-1 left-nav">
	<ul id="info-menu">
		<li id="show-all" class="active-item">All</li>
		<% @categories.each do |category| %>
			<% unless category.networks.nil? %>
				<li id=<%= category.name %>><%= link_to category.name.capitalize %></li>
			<% end %>	
		<% end %>
	</ul>
</div>

app/views/networks/_founder_field.html.erb
<%= f.text_field "founders[]", class: "form-input" %>

app/views/networks/_links.html.erb
<ul>
	<% if @network.links.empty? %>
		<div class="row">
			<div class="col-md-8 col-md-offset-4">
				<p class="add-first">No links yet. <%= link_to "Add one?", new_link_url(network: @network), remote: true %></p>
			</div>
		</div>
	<% else %>
		<%= render(partial: 'links/show_all_links', collection: @links, as: :link) %>
	<% end %>
</ul>

app/views/networks/_log.html.erb
<li class="log-block block">
	<div class="row">
		<div class="col-md-4">
    		<% unless log.networks.nil? %>
	    		<div class="user-log-classification">
					<div class="user-log-classification-network">
						<%= image_tag(log.networks.logo.small.url, size: "20x20") if log.networks.logo? %>
						<%= link_to truncate(log.networks.name, length: 16), log.networks %>
					</div>
				</div>
			<% end %>
			<h6 class="when-posted"><%= time_ago_in_words(log.created_at) %></h6>
			<% if defined?(current_user) %>
				<%= link_to log.user, class: "who-posted" do %>
    				<%= image_tag(log.user.avatar, size: '16x16', class: 'avatar') if defined?(log.user.avatar) %>
    				<% if defined?(log.user.username) %>
    					<%= current_user == log.user ? "Me" : log.user.username %>
    				<% end %>
    			<% end %>
    		<% elsif defined?(log.user) && !log.user.nil? %>
    			<%= link_to log.user, class: "who-posted" do %>
    				<%= image_tag(log.user.avatar, size: '16x16', class: 'avatar') %>
    				<%= log.user.username %>
    			<% end %>
    		<% end %>
		</div>
		<div class="col-md-8">
			<ul class="log-list"> 
				<% log.changes.each do |change| %>
					<li>
						<% case change[:change_attr] %>
							<% when "whitepapers" %>
								<% if change[:change_type] == "added" || change[:change_type] == "edited" %>
								<%= change[:change_attr].capitalize %>
									added
								<% end %>
							<% when "founders" %>
								<%= change[:change_attr].capitalize %>
								<% if change[:change_type] == "added" %>
									added: 
									<% change[:change].second.each_with_index do |change, i| %>
										<%= change %>
									<% end %>
								<% elsif change[:change_type] == "edited" %>
									changed from 
										<% change[:change].first.each_with_index do |c, i| %>
											<%= " and " if i + 1 == change[:change].first.length && change[:change].first.length != 1 %><%= c %><%= ",	" unless i + 1 == change[:change].first.length || i + 2 == change[:change].first.length  %>
										<% end %>
									to 
										<% change[:change].second.each_with_index do |c, i| %>
											<%= " and " if i + 1 == change[:change].second.length && change[:change].second.length != 1 %><%= c %><%= ",	" unless i + 1 == change[:change].second.length || i + 2 == change[:change].second.length || change[:change].first.length == 1 %>
										<% end %>
								<% end %>
							<% when "status" %>
								<%= change[:change_attr].capitalize %>
								<% if change[:change_type] == "added" %>
									added: 
									<% change[:change].second.each_with_index do |c, i| %>
										<%= c.first %>
									<% end %>
								<% elsif change[:change_type] == "edited" %>
									changed from 
										<% change[:change].first.each_with_index do |c, i| %>
											<%= c.first %>
										<% end %>
									to 
										<% change[:change].second.each_with_index do |c, i| %>
											<%= c.first %>
										<% end %>
								<% end %>
							<% when "Created" %>
								Created 
									<%= link_to log.networks.name, log.networks %>
							<% when "logo" %>
								New logo							
							<% else %>
								<%= change[:change_attr].capitalize %>
								<% if change[:change_type] == "added" %>
									added: "<%= change[:change].second.capitalize %>"
								<% elsif change[:change_type] == "edited" %>
									changed from "<%= change[:change].first %>" to "<%= change[:change].second.capitalize %>"
								<% end %>
						<% end %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</li>

app/views/networks/_logs.html.erb
<ul>
	<% if @logs.any? %>
		<%= render(partial: 'log', collection: @logs, as: :log) %>
	<% else %>
		<li>
			<div class="row">
				<div class="col-md-8 col-md-offset-4">
					<p>No logs yet. Logs will show up when someone makes changes to this coin.</p>
				</div>
			</div>
		</li>
	<% end %>
</ul>

app/views/networks/_network_frame_bottom.html.erb
		</div>
	</div>
</div>

app/views/networks/_network_main_info_header.html.erb
<div class="row">
	<div class="col-md-8 data col-md-offset-4">
		<% if network.logo.nil? || network.logo.blank? %>
			<%= image_tag "fallback/default.png", size: '60x60', id: 'network-logo' %>
		<% else %>
			<%= image_tag network.logo, size: '60x60', id: 'network-logo' %>
		<% end %>
		<h1 id="network-name"><%= network.name %></h1>
	</div>
</div>

app/views/networks/_whitepapers.html.erb
<ul>
	<li class="network-info-block block">
		<% @whitepapers.each do |wp| %>
			<div class="row">
				<div class="col-md-8 col-md-offset-4">
					<%= link_to wp do %>
						<p><%= wp.whitepaper_title %></p>
						<%= image_tag wp.whitepaper.thumb, class: "whitepaper-thumbnail" if wp.whitepaper.thumb  %>
					<% end %>
				</div>
			</div>
		<% end %>
	</li>
</ul>

app/views/networks/links.js.erb
$('.content').html("<%= j (render 'links') %>");
$('#details').removeClass("active-item");
$('#links').addClass("active-item");
$('.action-links').html('<li><%= link_to "Add new link", new_link_url(network: @network, obj_type: "network"), remote: true, class: "action-link", accesskey: "A" %></li>');

app/views/networks/new.html.erb
<% provide(:title, 'Add new network') %> 
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="row">
			<div class="col-md-8 col-md-offset-4">
				<h3>Add a new network</h3>
			</div>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/networks/whitepapers.html.erb
<ul>
	<% @whitepapers.each do |wp| %>
		<li><%= link_to wp.whitepaper_title, wp %></li>
	<% end %>
</ul>

app/views/networks/whitepapers.js.erb
$('.content').html("<%= j (render 'whitepapers') %>");
$('#details').removeClass("active-item");
$('#whitepapers').addClass("active-item");
$('.action-links').html('<li><%= link_to "Add new whitepaper", new_whitepaper_url(network: @network, obj_type: "network"), remote: true, class: "action-link", accesskey: "A" %></li>');