config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations'}, sign_up: 'signup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  resources :categories
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :searches
  resources :networks do
    resources :whitepapers, :links, :coins
  end
  resources :links do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  match 'networks/:network_id/coins/:id/logs', to:'coins#logs', via: 'get'
  match 'networks/:id/logs', to:'networks#logs', via: 'get'

  match '/search', to:"searches#results", via: "get"

  match '/account/', to:"users#edit", via: "get"
  match '/account/:id', to:"users#edit", via: "get"

  match '/about', to:'application#about', via: 'get'

  match 'finish/:id/', to: 'users#finish', :as => :finish, via: "get"

  match ':id/', to: 'users#show', via: "get"

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'signin', to: 'devise/sessions#new'
  end



end

app/models/whitepaper.rb
class Whitepaper < ApplicationRecord
	mount_uploader :whitepaper, WhitepaperUploader
	belongs_to :network
	extend FriendlyId
	friendly_id :whitepaper_title, use: [:slugged, :history]
	include PgSearch
	multisearchable :against => [:whitepaper_title, :fulltext]
	pg_search_scope :search, :against => :fulltext, :using => { :tsearch => { :prefix => true }}
	has_paper_trail :class_name => 'Version', :ignore => [:slug, :updated_at]
end

app/controllers/whitepapers_controller.rb
class WhitepapersController < ApplicationController
  before_action :set_whitepaper, only: [:show, :edit, :update, :destroy]

  def index
    @whitepapers = Whitepaper.all
  end

  def show
    @whitepaper = Whitepaper.friendly.find(params[:id]).whitepaper
  end

  def new
    @whitepaper = Whitepaper.new
  end

  def edit
  end

  def create
    @whitepaper = Whitepaper.new(whitepaper_params)

    respond_to do |format|
      if @whitepaper.save
        format.html { redirect_to @whitepaper, notice: 'Whitepaper attachment was successfully created.' }
        format.json { render :show, status: :created, location: @whitepaper }
      else
        format.html { render :new }
        format.json { render json: @whitepaper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @whitepaper.update(whitepaper_params)
        format.html { redirect_to @whitepaper.network, notice: 'Whitepaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @whitepaper }
      else
        format.html { render :edit }
        format.json { render json: @whitepaper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @whitepaper.destroy
    respond_to do |format|
      format.html { redirect_to whitepapers_url, notice: 'Whitepaper attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whitepaper
      @whitepaper = Whitepaper.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def whitepaper_params
      params.require(:whitepaper).permit(:network_id, :title, :whitepaper)
    end
end

app/helpers/whitepapers_helper.rb
module WhitepapersHelper
end

app/views/whitepapers/_form.html.erb
<%= form_for(@whitepaper) do |f| %>
  <% if whitepaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(whitepaper.errors.count, "error") %> prohibited this whitepaper from being saved:</h2>
      <ul>
      <% whitepaper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-4">
      <%= f.label "Network" %>
    </div>
    <div class="col-md-8">
      <%= f.select :network_id, options_for_select(Network.all.order("name ASC").map {|n| [n.name, n.id, {'data-icon' => n.logo}, {class: 'network-option'}]}, { selected: @coin.network }.delete_if {|k,v| v.nil?}), {}, {multiple: true, size: 8.5, id: "network-option"} %>
    </div>
  </div>
  <div class="row">
      <div class="col-md-4">
        <%= f.label "Title" %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :title %>
      </div>
    </div>
  <ul class="action-links">
    <li class="submit">
      <%= f.submit "Submit changes", class: "form-submit" %> 
    </li>
  </ul>
<% end %>

app/views/whitepapers/_index.html.erb
<ul>
	<li class="network-info-block block">
		<% @whitepapers.each do |wp| %>
			<div class="row">
				<div class="col-md-8 col-md-offset-4">
					<%= link_to network_whitepaper_path(wp.network, wp), remote:true do %>
						<p><%= wp.whitepaper_title %></p>
						<%= image_tag wp.whitepaper.thumb, class: "whitepaper-thumbnail" if wp.whitepaper.thumb  %>
					<% end %>
				</div>
			</div>
		<% end %>
	</li>
</ul>

app/views/whitepapers/_show.html.erb
<div class="whitepaper-cnt">
		<embed src=<%= @whitepaper.url %> width="100%" height="800" type='application/pdf'>
</div>

app/views/whitepapers/index.html.erb
<%= render(partial: "networks/network_frame", locals: {network: @whitepapers.first.network, active_item: "whitepapers"}) %>
<ul>
	<li class="network-info-block block">
		<% @whitepapers.each do |wp| %>
			<div class="row">
				<div class="col-md-8 col-md-offset-4">
					<%= link_to network_whitepapers_path(wp) do %>
						<p><%= wp.whitepaper_title %></p>
						<%= image_tag wp.whitepaper.thumb, class: "whitepaper-thumbnail" if wp.whitepaper.thumb  %>
					<% end %>
				</div>
			</div>
		<% end %>
	</li>
</ul>
<%= render(partial: "networks/network_frame_bottom") %>

app/views/whitepapers/index.js.erb
$('.content').html("<%= j (render 'index') %>");
$('#details').removeClass("active-item");
$('#whitepapers').addClass("active-item");
$('.action-links').html('<li><%= link_to "Add new whitepaper", new_network_whitepaper_url(network: @network), remote: true, class: "action-link", accesskey: "A" %></li>');

app/views/whitepapers/show.html.erb
<%= javascript_include_tag "pdf.js" %>
<script>PDFObject.embed(@whitepaper, ".whitepaper-cnt");</script>
<div class="row">
	<div class="whitepaper-cnt">
		<embed src=<%= @whitepaper.url %> width="500" height="375" type='application/pdf'>
	</div>
</div>

app/views/whitepapers/show.js.erb
$('.content').append("<%= j (render 'show') %>");
$('li.active-item').removeClass("active-item");
$('#whitepapers').addClass("active-item");
$('.action-links').html('<li><%= link_to "Add new whitepaper", new_network_whitepaper_url(network: @network), remote: true, class: "action-link", accesskey: "A" %></li>');
$(window).click(function() {
	$('.whitepaper-cnt').hide();
});
$(document).keyup(function(e) {
     if (e.keyCode == 27) { 
        $('.whitepaper-cnt').hide();
    }
});
$('.whitepaper-cnt').click(function(event){
    event.stopPropagation();
});