config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations'}, sign_up: 'signup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  resources :categories
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :searches
  resources :networks do
    resources :whitepapers, :links, :coins
  end
  resources :links do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  match 'networks/:network_id/coins/:id/logs', to:'coins#logs', via: 'get'
  match 'networks/:id/logs', to:'networks#logs', via: 'get'

  match '/search', to:"searches#results", via: "get"

  match '/account/', to:"users#edit", via: "get"
  match '/account/:id', to:"users#edit", via: "get"

  match '/about', to:'application#about', via: 'get'

  match 'finish/:id/', to: 'users#finish', :as => :finish, via: "get"

  match ':id/', to: 'users#show', via: "get"

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'signin', to: 'devise/sessions#new'
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :omniauthable, :omniauth_providers => [:twitter, :facebook, :google_oauth2]

  include CarrierWave::MiniMagick

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :username, use: [:slugged, :history]

  has_many :coins
  has_many :links
  has_many :comments
  has_many :networks
  has_many :logs, :foreign_key => 'whodunnit', :class_name => "Version"

  def email_required?
    super && provider.blank?
  end

  def password_required?
    super && provider.blank?
  end

  protected
    def confirmation_required?
      false
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def edit
    @user = User.friendly.find(params[:id])
    puts "params are #{params.inspect}"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Please check your email to confirm your email address"
    else
      render 'new'
    end
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update_attributes(user_params)
        if get_all_logs(@user.id).empty?
          redirect_to root_url
        else
          redirect_to @user
        end
    else
        render 'edit'
    end
  end

  def index
    @logs = get_all_logs.paginate(:page => params[:page], :per_page => 10)
    @logs.each do |log|
      puts log.inspect
      if log.change_type == "edited"
        puts log.change[:change].first
      end
      puts ""
      puts ""
    end
      respond_to do |format|
        format.html
        format.js
    end
  end

  def finish
    @user = User.find(params[:id])
    if @user.username.nil? || @user.username.blank?
      @user = User.find(params[:id])
    else  
      redirect_to root_url
    end
  end

  def show
    @user = User.friendly.find(params[:id])
    @logs = get_all_logs(@user.id).paginate(:page => params[:page], :per_page => 10)
      respond_to do |format|
        format.html
        format.js
        format.json
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :avatar, :email, :password, :password_confirmation, :username)
    end

    def get_all_logs(user_id=nil)
    
      links = []
      logs = []
      
      if user_id.nil?
        link_query = Link.all.limit(20)
      else
        link_query = User.find(user_id).links
      end
      
      link_query.each do |link| 
        log = LogService.new
        log.data = link
        log.set_metadata(user: link.user, created_at: link.created_at, feed_type: "link")
        add_networks_and_coins(log, link.networks, link.coins)
        links << log
      end

      network_logs = NetworkService.new
      net_logs = network_logs.get_all_the_logs
      net_logs.each do |log|
        logs << log
      end
      logs += links
      @logs = logs.sort_by{|log| log.created_at}.reverse
    end
    

    def add_networks_and_coins(log, networks, coins)
      if networks.any?
        log.networks = networks
        if coins.any?  
          network_names = [] 
          networks.each do |network|
            network_names << network.name
          end
          coins.each do |coin|
            if network_names.index coin.name
              coin_to_delete = coin
              log.coins = coins.reject {|coin| coin = coin_to_delete}
            end
          end
        end
      end
      return log
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, authenticity_token: true) do |f| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-4">
      <%= image_tag current_user.avatar, size: "60x60", id: "coin-logo" if @user.avatar? %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 label">
      <%= f.label "Avatar", class: "form-label" %>
    </div>
    <div class="col-md-8">
      <%= f.file_field :avatar, class: 'filestyle' %>
    </div>
  </div>
   <div class="row grouped-row grouped-row-first name-group">
    <div class="col-md-4 label">
      <%= f.label "First name", class: "form-label" %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :first_name, class: "form-input" %>
    </div>
  </div>
  <div class="row grouped-row grouped-row-last name-group">
    <div class="col-md-4 label">
      <%= f.label "Last name", class: "form-label" %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :last_name, class: "form-input" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 label">
      <%= f.label "Username", class: "form-label" %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :username, class: "form-input" %>
    </div>
  </div>
  <ul class="action-links">
    <li class="submit">
      <%= f.submit "Submit changes", class: "form-submit" %> 
    </li>
  </ul>
<% end %>

app/views/users/_info_menu.html.erb
<ul id="info-menu">
	<% if !@user.nil? %>
		<li class="active-item" id="account"><p><%= link_to "Account", '/account' %><p></li>
	<% end %>
	<li id="activity"><p><%= link_to "Activity", @user, remote: true %></p></li>
</ul>

app/views/users/_show.html.erb
<ul>
	<li class="user-header user-info-block block">
		<%= render(partial: 'user_main_info_header') %>
	</li>
	<%= content_tag(:div, content_tag(:div, content_tag(:li, "No activity yet"), class: "col-md-8 col-md-offset-4"), class: "row") if @logs.empty? %>
	<%= render 'shared/logs', locals: {logs: @logs} %>
</ul>

app/views/users/account.js.erb
$('.main').html("<%= j (render 'edit') %>");
$('#info-menu > li').removeClass("active-item");
$('#account').addClass("active-item");

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-1 left-nav">
    <%= render 'info_menu' %>
  </div>
  <div class="col-md-6 main">
    <%= render 'form' %>
  </div>
</div>

app/views/users/finish.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, authenticity_token: true, url:user_path do |f| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-4">
        <h3>Select a username</h3>
      </div>
    </div>
    <% if @user.email.nil? || @user.email.nil? %>
      <div class="row">
        <div class="col-md-4 label">
          <%= f.label "Email", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :email, class: "form-input" %>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-4 label">
        <%= f.label "Username", class: "form-label" %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :username, class: "form-input" %>
      </div>
    </div>
    <ul class="action-links">
      <li class="submit">
        <%= f.submit "Finish", class: "form-submit" %> 
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= javascript_include_tag "paginate_logs" %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<ul class="action-links">
			<li><%= link_to("New link", new_link_path, remote: false, class: "action-link", accesskey: 'L') %></li>
			<li><%= link_to("New network", new_network_path, remote: false, class: "action-link", accesskey: 'N') %></li>
		</ul>
		<ul class="feed">
			<li class="intro-header user-info-block block">
				<div class="row">
					<div class="col-md-12 intro-block">
						<h1>Welcome to the Coindexter beta</h1>
						<p>Coindexter is a way to discover up and coming blockchain networks and app coins. There are already a bunch of places on the web where you can view financials for live coins. Coindexter is where you can discover and talk about what's not yet live. You can edit the records for each network or coin, like a wiki, and share links and whitepapers and comment on them, like Reddit or Hacker News.</p>
						<p>The site doesn't quite convey that yet. I'm working on it. In the meantime I'm eager to get your feedback, and grateful for helping to get started crowdsourcing.</p>
						<p>To that end, here's some recent activity on Coindexter.</p>
					</div>
				</div>
			</li>
			<%= render 'shared/logs', locals: {logs: @logs} %>
			<div class="row">
				<div class="col-md-8 col-md-offset-4">
					<p class="loading-more">Loading more...</p>
				</div>
			</div>
			<%#= will_paginate @logs %>
		</ul>
	</div>
</div>

app/views/users/index.js.erb
$('.pagination').replaceWith('<%= escape_javascript(render "shared/logs", locals: {logs: @logs}) %>');
$('.feed').append('<%= escape_javascript will_paginate(@logs) %>');	
$('.loading-more').hide();

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-2 col-md-offset-1 left-nav">
		<%= render(partial: 'info_menu', object: {user: @user}) %>
	</div>
	<div class="col-md-6 main">
		<ul>
			<%= render 'form' %>
		</ul>
	</div>
</div>

app/views/users/show.js.erb
$('.main').html("<%= j (render 'show') %>");
$('#info-menu > li').removeClass("active-item");
$('#activity').addClass("active-item");

app/views/users/signin.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 main">
    <form class="sign-in-up">
      <div class="row">
        <div class="col-md-8 col-md-offset-4">
          <h6>sign in with email</h6>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 label">
          <label>Email</label>
        </div>
        <div class="col-md-8">
          <input type="text" id="email">
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 label">
          <label>Password</label>
        </div>
        <div class="col-md-8">
          <input type="password" id="password">
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-4">
          <button class="signin-db">Sign in with Email/Password</button>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-4">
          <h6>social sign in</h6>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 label">
          <label>google</label>
        </div>
        <div class="col-md-8">
          <button class="signin-google-popup">Sign in with Google</button>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 label">
          <label>twitter</label>
        </div>
        <div class="col-md-8">
          <button class="signin-twitter">Sign in with Twitter</button>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 label">
          <label>facebook</label>
        </div
        <div class="col-md-8">
          <button class="signin-facebook">Sign in with Facebook</button>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/users/update.html.erb
<div class="row">
	<div class="col-md-2 col-md-offset-1 left-nav">
		<%= render(partial: 'info_menu', object: {user: @user}) %>
	</div>
	<div class="col-md-6 main">
		<ul>
			<li class="user-header user-info-block block">
				<%= render(partial: 'user_main_info_header') %>
			</li>
			<% @logs.each do |log| %>
				<% if log.feed_type == "network_log" %>
					<%= render(partial: 'networks/log', locals: {log: log}) %>
					<div class="row">
						<div class="col-md-8 col-md-offset-4">
							<div class="user-log-classification">
								<p>Coin</p>
								<div class="user-log-classification-network">
									<%= image_tag(log.networks.logo.small.url, size: "20x20") %>
									<%= link_to log.networks.name, log.networks %>
								</div>
							</div>
						</div>
					</div>
				<% elsif log.feed_type == "coin_log" %>
					<%= render(partial: 'coins/log', locals: {log: log}) %>
					<div class="row">
						<div class="col-md-8 col-md-offset-4">
							<div class="user-log-classification">
								<p>Network</p>
								<div class="user-log-classification-coin">
									<%= image_tag(log.coins.logo.small.url, size: "20x20") %>
									<%= link_to log.coins.name, log.coins %>
								</div>
							</div>
						</div>
					</div>
				<% elsif log.feed_type == "link" %>
					<%= render(partial: 'links/show_all_links', locals: {link: log.data}) %>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>