config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations'}, sign_up: 'signup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  resources :categories
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :searches
  resources :networks do
    resources :whitepapers, :links, :coins
  end
  resources :links do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  match 'networks/:network_id/coins/:id/logs', to:'coins#logs', via: 'get'
  match 'networks/:id/logs', to:'networks#logs', via: 'get'

  match '/search', to:"searches#results", via: "get"

  match '/account/', to:"users#edit", via: "get"
  match '/account/:id', to:"users#edit", via: "get"

  match '/about', to:'application#about', via: 'get'

  match 'finish/:id/', to: 'users#finish', :as => :finish, via: "get"

  match ':id/', to: 'users#show', via: "get"

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'signin', to: 'devise/sessions#new'
  end



end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :network, optional: true
  mount_uploader :logo, LogoUploader
  extend FriendlyId
  include PgSearch
  multisearchable :against => [:name]
  pg_search_scope :search, :against => [:name, :symbol] , :using => { :tsearch => { :prefix => true } }

  validates_uniqueness_of :name

  friendly_id :name, use: [:slugged, :history]

  has_and_belongs_to_many  :links
  has_many :comments, through: :links

  has_paper_trail :class_name => 'Version', :ignore => [:price, :one_hour_price_change, :one_day_price_change, :volume, :market_cap, :available_supply, :total_supply, :link_id, :links_id, :slug, :updated_at, :category_id]

  enum coin_status_options: [:concept, :preproduction, :live, :dead]

  def should_generate_new_friendly_id?
	 !has_friendly_id_slug? || name_changed?
  end

  def has_friendly_id_slug?
    slugs.where(slug: slug).exists?
  end

  def one_day_up 
    if one_day_price_change > 0 
      self.one_day_up = "up"
    else
      self.one_day_up = "down"
    end
  end

  def one_hour_up 
    if one_hour_price_change > 0 
      self.one_hour_up = "up"
    else
      self.one_hour_up = "down"
    end
  end

  def update_prices
    response = HTTParty.get('https://api.coinmarketcap.com/v1/ticker/' + name.delete(" ").downcase)
    if response[0].nil?
      puts name
      update_attributes(:coin_status => 'concept')
    else
      price = response[0]["price_usd"]
      one_hour_price_change = response[0]["percent_change_1h"]
      one_day_price_change = response[0]["percent_change_24h"]
      available_supply = response[0]["available_supply"]
      total_supply = response[0]["total_supply"]
      market_cap = response[0]["market_cap_usd"]
      update_attributes(:price => price,:one_day_price_change => one_day_price_change, :one_hour_price_change => one_hour_price_change, :available_supply => available_supply, :total_supply => total_supply, :market_cap => market_cap)
    end
  end

  def repositories
    read_attribute(:repositories).map {|v| Repository.new(v) }
  end

  class Repository
    attr_accessor :name, :url

    def initialize(hash)
      @name = hash['name']
      @url = hash['url']
    end

    def persisted?() false; end
    def new_record?() false; end
    def marked_for_destruction?() false; end
    def _destroy() false; end

  end

  def repositories_attributes=(attributes)
    repositories = []
    attributes.each do |index, attrs|
      next if attrs["_destroy"] == true
      repositories << attrs
    end
    repository_changed(repositories)
  end

  def build_repository
    r = self.repositories.dup
    r << Repository.new({name: '', url: ''})
    self.repositories = r
  end

  def repository_changed(repos)
    any_changes = false
    if self.repositories.length != repos.length
      any_changes = true
    else
      self.repositories.each_with_index do |repository, i|
        if repository.name != repos[i]["name"] || repository.url != repos[i]["url"]
          any_changes = true
        end
      end
    end
    if any_changes
      write_attribute(:repositories, repos)
    end
  end

  def exchanges
    read_attribute(:exchanges).map {|v| Exchange.new(v) }
  end

  class Exchange
    attr_accessor :name, :url

    def initialize(hash)
      @name = hash['name']
      @url = hash['url']
    end

    def persisted?() false; end
    def new_record?() false; end
    def marked_for_destruction?() false; end
    def _destroy() false; end

  end

  def exchanges_attributes=(attributes)
    exchanges = []
    attributes.each do |index, attrs|
      next if attrs["_destroy"] == true
      exchanges << attrs
    end
    exchange_changed(exchanges)
  end

  def build_exchange
    e = self.exchanges.dup
    e << Exchange.new({name: '', url: ''})
    self.exchanges = e
  end

  def exchange_changed(xchanges)
    any_changes = false
    if self.exchanges.length != xchanges.length
      any_changes = true
    else
      self.exchanges.each_with_index do |exchange, i|
        if exchange.name != xchanges[i]["name"] || exchange.url != xchanges[i]["url"]
          any_changes = true
        end
      end
    end
    if any_changes
      write_attribute(:exchanges, xchanges)
    end
  end  

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController

	before_action :authenticate_user!, only: [:edit,:new,:create,:update]

	def index
		page_title = "Coins"
		coins = Coin.all.order("market_cap DESC")
		@coins_live = coins.reject {|c| c.coin_status != "live"}
		@coins_preproduction = coins.reject {|c| c.coin_status != "preproduction"}
		@coins_concept = coins.reject {|c| c.coin_status != "concept"}
		@coins_dead = coins.reject {|c| c.coin_status != "dead"}
	end

	def links
		@links = Coin.friendly.find(params[:id]).links.paginate(:page => params[:page], :per_page => 10)
		@coin = Coin.friendly.find(params[:id])
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def logs
        coin_logs = NetworkService.new
        @coin = Coin.friendly.find(params[:id]) 
        logs = coin_logs.get_logs(@coin, "coin_log").reverse
        @logs = logs.paginate(:page => params[:page], :per_page => 10)
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end	

	def show
		@coin = Coin.friendly.find(params[:id])
		respond_to do |format|
		    format.html
		    format.js
		    format.json
		end
	end

	def new
		@use_ajax = true
		@coin = Coin.new
		@coin.build_repository
	end

	def edit
		@use_ajax = false
		@coin = Coin.friendly.find(params[:id])
		if @coin.repositories.empty?
			@coin.build_repository
		end
		if @coin.exchanges.empty?
			@coin.build_exchange
		end
	end

	def create
		@coin = Coin.new(coin_params)
	    if @coin.save
	    	@coin.category_id = 2 ? @coin.category_id.nil? : @coin.category_id
	    	@coin.update_prices
	    	@coin.save
			redirect_to @coin
		else
	        render 'new'
	    end
	end

	def update
		@coin = Coin.friendly.find(params[:id])
	  	if @coin.update_attributes(coin_params)
	    	redirect_to @coin
		else
	    	render 'edit'
	  	end
	end

	def destroy
		@coin.destroy
	end

	private

	    def coin_params
	    	params.require(:coin).permit(:name, :symbol, :coin_status, :coin_info, :application_name, :application_description, :application_status, :application_url, :category_id, :logo, :slug, :coin_type, :network_id, networks: [], network_ids: [], exchanges: {}, repositories: {}, repositories_attributes: [:name, :url, :_destroy], exchanges_attributes: [:name, :url, :_destroy])
	    end

		def up_or_down(value)
			if value > 0
				return "up"
			else
				return "down"
			end
		end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_coins_in_statuses.html.erb
<% unless status_group.empty? %>
	<ul id="<%= status.downcase %>" class="status-group">
		<li class="status-coin-block block">
			<div class="row">
				<div class="col-md-10 col-md-offset-2">
					<div class="row coins-in-statuses <%= status.first %>" > 
						<h1 class="list-name"><%= status %></h1>
						<% status_group.each_with_index do |coin, i| %>		
							<%= render 'coin_widget', :coin => coin, :i => i %>
						<% end %>
					</div>
				</div>
			</div>
		</li>
	</ul>
<% end %>

app/views/coins/_log.html.erb
<li class="log-block block">
	<div class="row">
		<div class="col-md-4">
			<% if defined?(log.coins) && !log.coins.nil? %>
	    		<div class="user-log-classification">
					<div class="user-log-classification-network">
						<%= image_tag(log.coins.logo.small.url, size: "20x20") if log.coins.logo? %>
						<%= link_to truncate(log.coins.name, length: 16	), network_coin_path(log.coins.network, log.coins) %>
					</div>
				</div>
			<% end %>
			<h6 class="when-posted"><%= time_ago_in_words(log.created_at) %></h6>
			<% if defined?(current_user) %>
				<%= link_to log.user, class: "who-posted" do %>
    				<%= image_tag(log.user.avatar, size: '20x20', class: 'avatar') if defined?(log.user.avatar) %>
    				<% if defined?(log.user.username)%>
    					<%= current_user == log.user ? "Me" : log.user.username %>
    				<% end %>
    			<% end %>
    		<% elsif defined?(log.user) && !log.user.nil? %>
    			<%= link_to log.user, class: "who-posted" do %>
    				<%= image_tag(log.user.avatar, size: '16x16', class: 'avatar') %>
    				<%= log.user.username %>
    			<% end %>
    		<% end %>
		</div>
		<div class="col-md-8">
			<ul class="log-list"> 
				<% log.changes.each do |change| %>
					<li>
						<% case change[:change_attr] %>
							<% when "Repositories", "Exchanges" %>
									<%= change[:change_attr].capitalize %>
									<% if change[:change_type] == "added" %>
										added: 
											<% puts "log is #{change[:change].second}" %>
											<%= link_to change[:change].second.first["name"], change[:change].second.first["url"] %>
									<% elsif change[:change_type] == "edited" %>
										changed from 
											<% change[:change].first.each_with_index do |change, i| %>
												<%= link_to change["name"], change["url"] %>
											<% end %>
										to 
											<% change[:change].second.each_with_index do |change, i| %>
												<%= link_to change["name"], change["url"] %>
											<% end %>
									<% end %>
							<% when "Network", "Description" %>
								<%= change[:change_attr].capitalize %>
								<% if change[:change_type] == "added" %>
									added:
									<%= link_to change[:change].second.name, change[:change].second unless change[:change].nil? %>
								<% elsif change[:change_type] == "edited" %>
									changed from 
										<% change[:change].first.each_with_index do |change, i| %>
											<%= link_to change["name"], change unless change.nil? %><%= "," unless i + 1 == change[:change].second.length %>
										<% end %>
									to 
										<% change[:change].second.each_with_index do |change, i| %>
											<%= link_to change["name"], change unless change.nil? %>
										<% end %>
								<% end %>
							<% when "Created" %>
								Created 
								<%= link_to log.coins.name, log.coins %>
							<% when "logo" %>
								New logo
							<% else %>
								<%= change[:change_attr].capitalize %>
								<% if change[:change_type] == "added" %>
									added: "<%= change[:change].second.capitalize %>"
								<% elsif change[:change_type] == "edited" %>
									changed from "<%= change[:change].first %>" to "<%= change[:change].second.capitalize %>"
								<% end %>
						<% end %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</li>

app/views/coins/_logs.html.erb
<%= javascript_include_tag 'paginate_logs' %>
<ul class="outer-log-list">
	<% if @logs.any? %>
		<%= render(partial: 'log', collection: @logs, as: :log) %>
	<% else %>
	<li>
		<div class="row">
			<div class="col-md-8 col-md-offset-4">
				<p>No logs yet. Logs will show up when someone makes changes to this coin.</p>
			</div>
		</div>
	</li>
	<% end %>
</ul>

app/views/coins/_show_coin.html.erb
<ul id="<%= @coin.name %> show-coin">
	<li class="coin-main-info coin-info-block block">
		<div class="row">
			<div class="col-md-4 label">
				<h6>status</h6>
			</div>
			<div class="col-md-8 data <%= 'status' unless @coin.coin_status.nil? || @coin.coin_status == '' %>">
				<% if @coin.coin_status.nil? || @coin.coin_status == "" %>
					<%= link_to "Add its status", edit_network_coin_url, class: "add-missing-field" %>
				<% else %>
					<div class="status-icon <%= @coin.coin_status.downcase %>-icon"></div>
					<p class="status <%= @coin.coin_status.downcase %>-status"><%= @coin.coin_status.downcase %></p>
				<% end %>
			</div>
		</div>
		<div class="row">
			<% unless @coin.coin_status == "" %>
				<div class="col-md-4 label">
					<h6>Exchange</h6>
				</div>
				<div class="col-md-8 data">
					<% if @coin.exchanges.nil? || @coin.exchanges == "" %>
						<%= link_to "Add an exchange", edit_network_coin_url, class: "add-missing-field" %>
					<% else %>
						<ul>
						<% @coin.exchanges.each_with_index do |exchange, i| %>
							<li><%= link_to exchange.name, exchange.url %></li>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
		<div class="row">
			<div class="col-md-4 label">
				<h6>additional</h6>
			</div>
			<div class="col-md-8 data">
				<% if @coin.application_description.nil? || @coin.application_description == "" %>
					<%= link_to "Add additional information", edit_network_coin_url, class: "add-missing-field" %>
				<% else %>
					<p><%= @coin.coin_info %></p>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 label">
				<h6>Networks</h6>
			</div>
			<div class="col-md-8">
				<% unless @coin.network.nil? %>
					<%= link_to @coin.network.name, @coin.network %>
				<% else %>
					<%= link_to "Add a network to #{@coin.name}", edit_network_coin_url, class: "add-missing-field" %>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 label">
				<h6>Symbol</h6>
			</div>
			<div class="col-md-8 symbol">
				<% unless @coin.symbol.nil? %>
					<%= @coin.symbol %>
				<% else %>
					<%= link_to "Add a symbol to #{@coin.name}", edit_network_coin_url, class: "add-missing-field" %>
				<% end %>
			</div>
		</div>
	</li>
	<% unless @coin.coin_status != 'live' || @coin.market_cap.nil? %>
		<li class="coin-price-info @coin-info-block block">
			<div class="row">
				<div class="col-md-4 label">
					<h6>price (usd)</h6>
				</div>
				<div class="col-md-8 data">
					<p><%= number_to_currency(@coin.price, :unit => '$') unless @coin.price.nil? %></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 label">
					<h6>1d</h6>
				</div>
				<div class="col-md-8 data">
					<p><span class=<%= @one_day_up %>><%= @coin.one_day_price_change unless @coin.one_day_price_change.nil? %>%</span></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 label">
					<h6>1h</h6>
				</div>
				<div class="col-md-8 data">
					<p><span class=<%= @one_hour_up %>><%= @coin.one_hour_price_change unless @coin.one_hour_price_change.nil? %>%</span></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 label">
					<h6>Market cap</h6>
				</div>
				<div class="col-md-8 data">
					<p>$<%= number_to_human(@coin.market_cap, units: {thousand: "K", million: "mm", billion: "B"}).delete(' ') unless @coin.market_cap.nil? %></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 label">
					<h6>Available supply</h6>
				</div>
				<div class="col-md-8 data">
					<p><%= number_to_human(@coin.available_supply, units: {thousand: "K", million: "mm", billion: "B"}).delete(' ') unless @coin.available_supply.nil? %></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 label">
					<h6>Total supply</h6>
				</div>
				<div class="col-md-8 data">
					<p><%= number_to_human(@coin.total_supply, units: {thousand: "K", million: "mm", billion: "B"}).delete(' ') unless @coin.available_supply.nil? %></p>
				</div>
			</div>
		</li>
	<% end %>
	<li class="coin-info-block block">
		<div class="row">
			<div class="row">
				<div class="col-md-8 col-md-offset-4 title-row">
					<h6>technical</h6>
				</div>
			</div>	
			<div class="row">
				<div class="col-md-4 label">
					<h6>Repo</h6>
				</div>
				<div class="col-md-8">
					<% if @coin.repositories.empty? || @coin.repositories.first.name == ""  %>
						<%= link_to "Add a repository", edit_network_coin_url, class: "add-missing-field" %>
					<% else %>
						<% @coin.repositories.each_with_index do |repository, i| %>
							<div class="col-md-8 <%= "col-md-offset-4" unless i==0 %>">
								<%= link_to repository.name, repository.url %>
							</div>
						<% end %>
					<% end %>	
				</div>	
			</div>	
			<div class="row">
				<div class="col-md-4 label">
					<h6>Type</h6>
				</div>
				<div class="col-md-8">
					<% if @coin.coin_type.nil? || @coin.coin_type == "" %>
						<%= link_to "Add a type", edit_network_coin_url, class: "add-missing-field" %>
					<% else %>
						<p><%= @coin.coin_type.capitalize %></p>
					<% end %>
				</div>
			</div>	
		</div>
	</li>
</ul>

app/views/coins/alt-index.html.erb
<div class="row">
	<%= render 'coin_status_menu' %>
	<div class="col-md-6 main">
		<%= render(partial: "coins_in_statuses", locals: {status_group: @coins_live, status: "Live"}) %>
		<%= render(partial: "coins_in_statuses", locals: {status_group: @coins_preproduction, status: "Pre-production"}) %>
		<%= render(partial: "coins_in_statuses", locals: {status_group: @coins_concept, status: "Concept"}) %>
		<%= render(partial: "coins_in_statuses", locals: {status_group: @coins_dead, status: "Dead"}) %>
		<ul class="action-links">
			<li><%= link_to("Add new coin", new_network_coin_path, class: "action-link", accesskey: 'A') %></li>
		</ul>
	</div>
</div>

app/views/coins/alt-show.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="https://cdn.cryptowat.ch/assets/build/scripts/dist/embed.js"></script>
<% end %>
<div class="row">
	<div class="col-md-2 col-md-offset-1 left-nav">
		<%= render 'info_menu' %>
	</div>
	<div class="col-md-6 main ">
		<div class="info-header">
			<%= render 'coin_main_info_header', coin: @coin %>
		</div>
		<div class="content">
			<%= render 'show_coin' %>
		</div>
	</div>
	<ul class="action-links">
		<% if current_user %>
			<li><%= link_to("Edit #{@coin.name}", edit_coin_path, class: "action-link", accesskey: 'E') %></li>
		<% else %>
			<li><%= link_to("Edit #{@coin.name}", '/signin', class: "action-link", accesskey: 'E') %></li>
		<% end %>
	</ul>
</div>

app/views/coins/edit.html.erb
<% provide(:title, 'Edit #{coin.name}') %> 
<div class="row">
	<div class="col-md-6 col-md-offset-3 main">
		<%= render 'form' %>
	</div>
</div>

app/views/coins/edit.js.erb
$('.action-links').html("");
$('.main').html("<%= j (render 'form') %>");

app/views/coins/links.js.erb
$('.content').html("<%= j (render 'links') %>");
$('#info-menu > li').removeClass("active-item");
$('#links').addClass("active-item");
$('.action-links').html('<li><%= link_to "Add new link", new_link_url(coin: @coin, obj_type: "coin"), remote: true, class: "action-link", accesskey: "A" %></li>');

app/views/coins/logs.js.erb
$('.content').html("<%= j (render 'logs') %>");
$('#info-menu > li').removeClass("active-item");
$('#log').addClass("active-item");
$('.action-links').hide();

app/views/coins/new.html.erb
<% provide(:title, 'Add new coin') %> 
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="row">
			<div class="col-md-8 col-md-offset-4">
				<h3>Add a new coin</h3>
			</div>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/coins/new.js.erb
$('.action-links').hide();
$('.main').html("<%= j (render 'form') %>");